### ISSUE TITLE
Many errors while trying to use the extension

### ISSUE THREAD

**Issue by fharper** [mlazzje/gmail-dl-all-attachments-for-chrome#5]
I don't have the time to dig up right now, so I'm adding it here so someone else can give it a look: it's on Gmail, last version of Chrome (69.0.3497.100 64-bit) on mac (10.13.6).

![issue](https://user-images.githubusercontent.com/1170989/47103850-1cd69480-d20e-11e8-95ae-3c19e56f010e.png)

**Comment by mlazzje** [comment]
I can't reproduce this issue.

**Comment by fharper** [comment]
I'll let you know if I can reproduce, but it was 7 months ago, so maybe it was about Chrome.
